import { ZodIssueCode, type ZodErrorMap } from "zod";

/**
 * Zod's default messages, in Spanish and naming the field.
 *
 * A schema that spells out its own message keeps it: this only replaces the
 * defaults, which reached people as "Expected integer, received float" or
 * "String must contain at least 2 character(s)". Most schemas are generated by
 * drizzle-zod and cannot carry a message per rule, so the fix has to be here
 * rather than one .min(…, "…") at a time.
 *
 * The API answers with the first problem only, and without the form around it
 * nothing says which field that was. Hence the names below: "Falta la cantidad."
 * is an answer, "Falta este dato." is a riddle.
 */
const fieldNames: Record<string, string> = {
  name: "el nombre",
  description: "la descripción",
  contactInfo: "el contacto",
  address: "la dirección",
  sku: "el código SKU",
  categoryId: "la categoría",
  supplierId: "el proveedor",
  productId: "el producto",
  quantity: "la cantidad",
  sellingPrice: "el precio de venta",
  purchasePrice: "el precio de compra",
  purchaseUnits: "las unidades de la compra",
  unitLabel: "la unidad",
  imageUrl: "la imagen",
  items: "la venta",
  customerName: "el nombre del cliente",
  notes: "la nota",
  creditAccountId: "el fiado",
  amount: "el monto",
  paymentMethod: "el método de pago",
  ownerEmail: "el correo del dueño",
  ownerPassword: "la contraseña",
  slug: "el identificador",
  status: "el estado",
};

const numbers = new Intl.NumberFormat("es-EC");

/** The innermost named segment: items.0.quantity is about the quantity. */
function fieldOf(path: (string | number)[]): string | undefined {
  for (let index = path.length - 1; index >= 0; index -= 1) {
    const segment = path[index];
    if (typeof segment === "string") return fieldNames[segment];
  }
  return undefined;
}

export const spanishErrorMap: ZodErrorMap = (issue) => {
  const subject = fieldOf(issue.path) ?? "este dato";
  const plural = /^(los|las) /.test(subject);
  const Subject = subject[0].toUpperCase() + subject.slice(1);
  const verb = (singular: string, pluralForm: string) => (plural ? pluralForm : singular);
  const missing = `${verb("Falta", "Faltan")} ${subject}.`;

  switch (issue.code) {
    case ZodIssueCode.invalid_type:
      if (issue.received === "undefined" || issue.received === "null") return { message: missing };
      if (issue.expected === "integer") return { message: `${Subject} ${verb("debe", "deben")} ser un número entero.` };
      if (issue.expected === "number" || issue.expected === "bigint") return { message: `${Subject} ${verb("debe", "deben")} ser un número.` };
      if (issue.expected === "string") return { message: `${Subject} ${verb("debe", "deben")} ser un texto.` };
      return { message: `${Subject} no ${verb("tiene", "tienen")} un formato válido.` };

    case ZodIssueCode.too_small: {
      const minimum = numbers.format(issue.minimum);
      if (issue.type === "string") {
        return issue.minimum <= 1
          ? { message: missing }
          : { message: `${Subject} ${verb("debe", "deben")} tener al menos ${minimum} caracteres.` };
      }
      if (issue.type === "number" || issue.type === "bigint") {
        return issue.inclusive
          ? { message: `${Subject} ${verb("debe", "deben")} ser ${minimum} o más.` }
          : { message: `${Subject} ${verb("debe", "deben")} ser mayor que ${minimum}.` };
      }
      if (issue.type === "array" || issue.type === "set") {
        return { message: `${Subject} ${verb("debe", "deben")} tener al menos ${minimum} ${issue.minimum === 1 ? "elemento" : "elementos"}.` };
      }
      return { message: `${Subject} no ${verb("alcanza", "alcanzan")} el mínimo permitido.` };
    }

    case ZodIssueCode.too_big: {
      const maximum = numbers.format(issue.maximum);
      if (issue.type === "string") return { message: `${Subject} no ${verb("puede", "pueden")} superar los ${maximum} caracteres.` };
      if (issue.type === "number" || issue.type === "bigint") {
        return issue.inclusive
          ? { message: `${Subject} no ${verb("puede", "pueden")} ser mayor que ${maximum}.` }
          : { message: `${Subject} ${verb("debe", "deben")} ser menor que ${maximum}.` };
      }
      if (issue.type === "array" || issue.type === "set") return { message: `${Subject} no ${verb("puede", "pueden")} tener más de ${maximum} elementos.` };
      return { message: `${Subject} ${verb("supera", "superan")} el máximo permitido.` };
    }

    case ZodIssueCode.invalid_string:
      if (issue.validation === "email") return { message: "El correo no es válido." };
      return { message: `${Subject} no ${verb("tiene", "tienen")} un formato válido.` };

    case ZodIssueCode.invalid_enum_value:
    case ZodIssueCode.invalid_literal:
    case ZodIssueCode.invalid_union:
      return { message: `${Subject} no ${verb("es", "son")} una opción válida.` };

    case ZodIssueCode.invalid_date:
      return { message: "La fecha no es válida." };

    default:
      return { message: `Revisa ${subject}.` };
  }
};
